os: linux
sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev
    - g++-7
    - lcov
    - gcovr
    update: true

cache:
  apt: true
  directories:
  - $HOME/.hunter

env: CC_EVAL=gcc-7 CXX_EVAL=g++-7

before_install:
- export CXX=$CXX_EVAL
- export CC=$CC_EVAL
- pip install --user cpplint

# CMAKE_EXE_LINKER need to bugfix: https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed
script:
- files=`find . -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"`
# sanitaizer check
- ( for file in $files; do cpplint --filter=-whitespace/braces,-whitespace/indent,-whitespace/comments $file || exit; done );
- ./tools/polly/bin/polly --reconfig --toolchain sanitize-address --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"
# clang-check
- ./tools/polly/bin/polly --reconfig --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold" CMAKE_EXPORT_COMPILE_COMMANDS=ON
- ( for file in $files; do echo $file; clang-check -analyze $file -p _builds/default-Release || exit; done );
# tests
- export CTEST_OUTPUT_ON_FAILURE=true
- ./tools/polly/bin/polly --reconfig --test --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"
# coverage logging
- ./tools/polly/bin/polly --toolchain gcc --reconfig --config Debug --test --fwd ENABLE_COVERAGE=yes
- ./tools/polly/bin/polly --toolchain gcc --reconfig --config Debug --target gcov
- gcovr -r  .
# coverage deploy
- ./tools/polly/bin/polly --toolchain gcc --reconfig --config Debug --target lcov
- ./tools/polly/bin/polly --toolchain gcc --reconfig --config Debug --target lcov-genhtml

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _builds/gcc-Debug/lcov/html/selected_targets
  github_token: $GITHUB_TOKEN # set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
